FROM jupyter/minimal-notebook:latest AS base

USER root
WORKDIR /
LABEL maintainer="TACC-Carlos D. <carlosd@tacc.utexas.edu>"
ARG DEBIAN_FRONTEND=noninteractive

# Build essentials for g++ compiler (for cartopy)
# Git for cloning Kalpana repo
RUN apt-get update && \
    apt-get install -y \
        git \
        build-essential \ 
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Python wants to build from 
SHELL ["/bin/bash", "-o", "pipefail", "-c", "-i"]
RUN mamba install -y -c conda-forge \
        python=3.11 \
        fiona \
        cmocean \
        matplotlib \
        numpy \
        geopandas \
        pandas \
        shapely \
        netCDF4 \
        simplekml \
        scipy \
        pathlib \
        rioxarray \
        cartopy \
        pyproj && \
	mamba clean --all -f -y 

RUN git clone https://github.com/TACC/Kalpana Kalpana && cd Kalpana && mkdir data

# Set the working directory to the Kalpana directory
WORKDIR /Kalpana/data

# Activate the kalpana conda environment and set the entrypoint to the Kalpana_N.py script
# RUN echo "source activate kalpana" > /etc/profile.d/conda.sh
ENTRYPOINT ["python", "../Kalpana_N.py"]